openapi: "3.0.1"
info:
  title: "Home Assistant Plugin"
  description: "A plugin that allows the user to control smart home devices via Home Assistant."
  version: "v1"
servers:
  - url: "https://creative-praline-359ad5.netlify.app/.netlify/functions/proxy"
paths:
  /api/services/light/turn_on:
    post:
      operationId: "turnOnLight"
      summary: "Turn on a light entity"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                entity_id:
                  type: "string"
                  description: "The entity ID of the light to turn on."
                brightness_pct:
                  type: "integer"
                  description: "The brightness percentage to set (0 to 100)."
      responses:
        "200":
          description: "OK"
  /api/services/light/turn_off:
    post:
      operationId: "turnOffLight"
      summary: "Turn off a light entity"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                entity_id:
                  type: "string"
                  description: "The entity ID of the light to turn off."
      responses:
        "200":
          description: "OK"
  /api/services/media_player/media_play_pause:
    post:
      operationId: "playPauseMedia"
      summary: "Play or pause a media player entity"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                entity_id:
                  type: "string"
                  description: "The entity ID of the media player to play or pause."
      responses:
        "200":
          description: "OK"
components: {}
